### ISSUE TITLE
Time history from power spectrum

### ISSUE THREAD

**Issue by AniketSanjayDesai** [gauthamrdy/earthquakepy#5]
A code for generating multiple random velocity time histories compatible/equivalent to a single power spectrum is requested.

**Comment by dbpatankar** [comment]
As you need multiple time histories from single power spectrum, there must be some assumption related to probability distribution of Fourier Coefficients. Do you have any journal article to refer to?

**Comment by dbpatankar** [comment]
In lieu of this information, at least we need to know the origin of the power spectrum (i.e. from which kind of time series the power spectrum is generated (is it from response time history of a system or input time history)?

**Comment by dbpatankar** [comment]
Feature added in recent version. 
Use as follows : 

# Read time series
`vel = ep.read_raw_file("filename")`

# Get its power spectrum
`ps = vel.get_power_spectrum()`

# Get timehistories compatible to power spectrum (ps)
`th = ps.get_compatible_timehistories(m=5)    # m = number of compatible timehistories required`
